### PR TITLE
Update PPA to new location

### PR DESCRIPTION
**Pull request by jeroen**

### CODE REVIEW

**Comment by chartgerink** [comment]
Need a bit more context for me to be able to judge whether I want to merge this PR. Any supporting docs on that this transfer took place or is preferred?

**Comment by chartgerink** [comment]
Considering I didn't get a reply I'm closing this PR.

**Comment by jeroen** [comment]
I am the owner of this PPA. If you actually run the code you notice that the old one no longer exists.

**Comment by chartgerink** [comment]
If you're coming in to a project for the first time, make an empty comment on the pull request, and subsequently don't provide a response I am not merging. 

Please consult the code of conduct and use common courtesy on a next PR.

**Pull request closed without merging**
